spring.application.name=transactionExecution

spring.main.web-application-type=reactive

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/financial_db
spring.r2dbc.username=us3r4dm1n
spring.r2dbc.password=4dm1npa55

