spring.application.name=transactionExecution

spring.main.web-application-type=reactive

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/tu_base_de_datos
spring.r2dbc.username=tu_usuario
spring.r2dbc.password=tu_password

