spring.application.name=transactionExecution

server.tomcat.threads.max=500
server.tomcat.threads.min-spare=50
server.tomcat.max-connections=10000

spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10

spring.jpa.open-session-in-view=false

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true